package com.dmdbrands.gurus.weight.domain.model.api.integration

data class UserAccount(
    val id: String,
    val firstName: String,
    val lastName: String?,
    val email: String,
    val dob: String,
    val gender: String,
    val zipcode: String?,
    val weightUnit: String?,
    val height: Float?,
    val activityLevel: String?,
    val goalWeight: Float?,
    val goalType: String?,
    val initialWeight: Float?,
    val metPreviousGoal: Boolean?,
    val percent: Float?,
    val isWeightlessOn: Boolean?,
    val weightlessWeight: Float?,
    val weightlessTimestamp: String?,
    val isStreakOn: Boolean?,
    val streakTimestamp: String?,
    val shouldSendEntryNotifications: Boolean?,
    val shouldSendWeightInEntryNotifications: Boolean?,
    val dashboardMetrics: List<String>?, // or List<BodyMetric> if you have a model
    val dashboardType: String?,
    val isFitbitOn: Boolean,
    val isGoogleFitOn: Boolean,
    val isMFPOn: Boolean,
    val isUAOn: Boolean,
    val isFitbitValid: Boolean,
    val isGoogleFitValid: Boolean,
    val isMFPValid: Boolean,
    val isUAValid: Boolean,
    val isHealthKitOn: Boolean?,
    val isHealthConnectOn: Boolean?,
    val accessToken: String?,
    val refreshToken: String?,
    val expiresAt: String?,
    val loggedIn: Int?,
)
