//
//  AccessibilityID+Settings.swift
//  Settings feature — Settings home, Account, Edit Profile, Change Password, Goal Setting.
//

extension AccessibilityID {
    // MARK: - Settings Screen rows
    static let settingsRowUserProfile = "settings_row_user_profile"
    static let settingsRowGoalSetting = "settings_row_goal_setting"
    static let settingsRowUnitType = "settings_row_unit_type"
    static let settingsRowWeightless = "settings_row_weightless"
    static let settingsRowBiologicalSex = "settings_row_biological_sex"
    static let settingsRowActivityLevel = "settings_row_activity_level"
    static let settingsRowHeight = "settings_row_height"
    static let settingsRowLogOut = "settings_row_log_out"
    // Value matches the Android testTag `settings_row_logout_all` byte-for-byte (MOB-1489).
    static let settingsRowLogoutAll = "settings_row_logout_all"
    static let settingsRowMyKids = "settings_row_my_kids"
    static let settingsRowAppPermissions = "settings_row_app_permissions"
    static let settingsRowMessages = "settings_row_messages"
    static let settingsRowNotifications = "settings_row_notifications"
    static let settingsRowAppearance = "settings_row_appearance"
    static let settingsRowDefaultGraphView = "settings_row_default_graph_view"
    static let settingsRowHelp = "settings_row_help"
    // Support section rows — values mirror the Android testTags (MOB-1489).
    static let settingsRowPrivacyPolicy = "settings_row_privacy_policy"
    static let settingsRowTermsOfService = "settings_row_terms_of_service"
    static let settingsRowGreaterGoods = "settings_row_greater_goods"
    static let settingsRowSwitchAccounts = "settings_row_switch_accounts"
    static let settingsRowDeleteAccount = "settings_row_delete_account"

    // MARK: - Account Settings / Add Scale rows
    static let accountSettingsAddScalesRow = "account_settings_add_scales_row"
    static let accountSettingsIntegrationsRow = "account_settings_integrations_row"
    static let accountSettingsExportDataRow = "account_settings_export_data_row"
    static let accountSettingsChangePasswordRow = "account_settings_change_password_row"
    static let accountSettingsUserProfileRow = "account_settings_user_profile_row"

    // MARK: - Edit Profile Screen
    static let firstNameField = "first_name_field"
    static let lastNameField = "last_name_field"
    static let emailField = "email_field"
    static let zipcodeField = "zipcode_field"
    static let profileSaveButton = "profile_save_button"

    // MARK: - Change Password Screen
    static let currentPasswordField = "current_password_field"
    static let newPasswordField = "new_password_field"
    static let confirmPasswordField = "confirm_password_field"
    static let changePasswordSaveButton = "change_password_save_button"

    // MARK: - Integrations
    static let integrationsScreenRoot = "integrations_screen_root"
    static let integrationsRequestButton = "integrations_request_button"
    static let integrationRow = "integration_row" // suffixed with the provider (e.g. _fitbit)

    // MARK: - Add & Edit Scales
    static let addEditScalesScreenRoot = "add_edit_scales_screen_root"
    static let addScaleModelNumberField = "add_scale_model_number_field"
    static let addScaleSubmitButton = "add_scale_submit_button"
    static let addScaleCantFindButton = "add_scale_cant_find_button"
    static let deviceRow = "device_row" // suffixed with the device SKU per row

    // MARK: - Goal Setting Screen
    static let goalSettingScreenRoot = "goal_setting_screen_root"
    static let goalWeightInput = "goal_weight_input"
    static let startingWeightInput = "starting_weight_input"
    static let goalSaveButton = "goal_save_button"
    static let goalMaintainTab = "goal_maintain_tab"
    static let goalLoseGainTab = "goal_lose_gain_tab"

    // MARK: - Weightless Screen
    static let weightlessScreenRoot = "weightless_screen_root"
    static let weightlessToggle = "weightless_toggle"
    static let weightlessSaveButton = "weightless_save_button"
    static let weightlessField = "weightless_field"
}

// MARK: - MOB-1489 accessibility-id sweep (declared centrally)
extension AccessibilityID {
    static let addBabyScreenRoot = "add_baby_screen_root"
    static let additionalSettingsClearDataRow = "additional_settings_clear_data_row"
    static let additionalSettingsCloseButton = "additional_settings_close_button"
    static let additionalSettingsEndAnimationToggle = "additional_settings_end_animation_toggle"
    static let additionalSettingsHelpButton = "additional_settings_help_button"
    static let additionalSettingsResetFirmwareRow = "additional_settings_reset_firmware_row"
    static let additionalSettingsRestoreFactoryRow = "additional_settings_restore_factory_row"
    static let additionalSettingsScreenRoot = "additional_settings_screen_root"
    static let additionalSettingsStartAnimationToggle = "additional_settings_start_animation_toggle"
    static let additionalSettingsTimeFormatRow = "additional_settings_time_format_row"
    static let appPermissionsScreenRoot = "app_permissions_screen_root"
    static let bpmSettingsBackButton = "bpm_settings_back_button"
    static let bpmSettingsBluetoothRow = "bpm_settings_bluetooth_row"
    static let bpmSettingsDeleteButton = "bpm_settings_delete_button"
    static let bpmSettingsDeviceNameRow = "bpm_settings_device_name_row"
    static let bpmSettingsProductGuideRow = "bpm_settings_product_guide_row"
    static let bpmSettingsScreenRoot = "bpm_settings_screen_root"
    static let changePasswordForgotPasswordButton = "change_password_forgot_password_button"
    static let changePasswordScreenRoot = "change_password_screen_root"
    static let deviceBluetoothAuthorizedRow = "device_bluetooth_authorized_row"
    static let deviceBluetoothBackButton = "device_bluetooth_back_button"
    static let deviceBluetoothOnRow = "device_bluetooth_on_row"
    static let deviceBluetoothScreenRoot = "device_bluetooth_screen_root"
    static let deviceLogCloseButton = "device_log_close_button"
    static let deviceLogRow = "device_log_row"
    static let deviceLogScreenRoot = "device_log_screen_root"
    static let deviceModesBackButton = "device_modes_back_button"
    static let deviceModesHelpButton = "device_modes_help_button"
    static let deviceModesSaveButton = "device_modes_save_button"
    static let deviceModesScreenRoot = "device_modes_screen_root"
    static let deviceNameBackButton = "device_name_back_button"
    static let deviceNameField = "device_name_field"
    static let deviceNameSaveButton = "device_name_save_button"
    static let deviceNameScreenRoot = "device_name_screen_root"
    static let deviceSettingsBackButton = "device_settings_back_button"
    static let deviceSettingsBluetoothRow = "device_settings_bluetooth_row"
    static let deviceSettingsDeleteButton = "device_settings_delete_button"
    static let deviceSettingsDisplayMetricsRow = "device_settings_display_metrics_row"
    static let deviceSettingsEnableBodyMetricsButton = "device_settings_enable_body_metrics_button"
    static let deviceSettingsModeRow = "device_settings_mode_row"
    static let deviceSettingsOtherSettingsRow = "device_settings_other_settings_row"
    static let deviceSettingsProductGuideRow = "device_settings_product_guide_row"
    static let deviceSettingsScaleNameRow = "device_settings_scale_name_row"
    static let deviceSettingsScreenRoot = "device_settings_screen_root"
    static let deviceSettingsSessionImpedanceToggle = "device_settings_session_impedance_toggle"
    static let deviceSettingsSetupWifiButton = "device_settings_setup_wifi_button"
    static let deviceSettingsSoftwareUpdateRow = "device_settings_software_update_row"
    static let deviceSettingsUsersRow = "device_settings_users_row"
    static let deviceSettingsWifiMacRow = "device_settings_wifi_mac_row"
    static let deviceSettingsWifiRow = "device_settings_wifi_row"
    static let displayMetricsSaveButton = "display_metrics_save_button"
    static let displayMetricsScreenRoot = "display_metrics_screen_root"
    static let displayMetricsWeightOnlyUpdateButton = "display_metrics_weight_only_update_button"
    static let editProfileBirthdayField = "edit_profile_birthday_field"
    static let editProfileScreenRoot = "edit_profile_screen_root"
    static let helpCallButton = "help_call_button"
    static let helpDeviceCategoryRow = "help_device_category_row"
    static let helpEmailButton = "help_email_button"
    static let helpManualInfoButton = "help_manual_info_button"
    static let helpScreenRoot = "help_screen_root"
    static let iamScreenRoot = "iam_screen_root"
    static let myAccountsLoginButton = "my_accounts_login_button"
    static let myAccountsScreenRoot = "my_accounts_screen_root"
    static let myAccountsSignupButton = "my_accounts_signup_button"
    static let myKidsAddBabyButton = "my_kids_add_baby_button"
    static let myKidsBabyRow = "my_kids_baby_row"
    static let myKidsEditBabyButton = "my_kids_edit_baby_button"
    static let myKidsSaveBabyButton = "my_kids_save_baby_button"
    static let myKidsScreenRoot = "my_kids_screen_root"
    static let softwareUpdateCloseButton = "software_update_close_button"
    static let softwareUpdateDateButton = "software_update_date_button"
    static let softwareUpdateSaveButton = "software_update_save_button"
    static let softwareUpdateScreenRoot = "software_update_screen_root"
    static let softwareUpdateTimeButton = "software_update_time_button"
    static let softwareUpdateUpgradeNowButton = "software_update_upgrade_now_button"
    static let troubleshootingClearDataRow = "troubleshooting_clear_data_row"
    static let troubleshootingCloseButton = "troubleshooting_close_button"
    static let troubleshootingRateAppRow = "troubleshooting_rate_app_row"
    static let troubleshootingResyncEntriesRow = "troubleshooting_resync_entries_row"
    static let troubleshootingScreenRoot = "troubleshooting_screen_root"
    static let troubleshootingSendAppLogRow = "troubleshooting_send_app_log_row"
    static let troubleshootingSendScaleLogRow = "troubleshooting_send_scale_log_row"
    static let usersBackButton = "users_back_button"
    static let usersNameField = "users_name_field"
    static let usersSaveButton = "users_save_button"
    static let usersScreenRoot = "users_screen_root"
    static let wifiMacBackButton = "wifi_mac_back_button"
    static let wifiMacCopyButton = "wifi_mac_copy_button"
    static let wifiMacScreenRoot = "wifi_mac_screen_root"
}
