package com.greatergoods.meapp.features.historyDetail.strings

object HistoryDetailScreenStrings {
    const val BackButtonContentDescription = "Go back"
    const val WeightUnit = "lbs"
    const val EntryDetailContentDescription = "View entry details"
    const val MoreDetailsButton = "More Details"
    const val DeleteButton = "Delete"
    const val DeleteEntryContentDescription = "Delete entry"
    const val BmiLabel = "Body Mass Index"
    const val BodyFatLabel = "Body Fat"
    const val MuscleMassLabel = "Muscle Mass"
    const val BodyWaterLabel = "Body Water"
    const val HeartRateLabel = "Heart Rate"
    const val BoneMassLabel = "Bone Mass"
    const val VisceralFatLabel = "Visceral Fat"
    const val SubcutaneousFatLabel = "Subcutaneous Fat"
    const val ProteinLabel = "Protein"
    const val SkeletalMuscleLabel = "Skeletal Muscle"
    const val BmrLabel = "Basal Metabolic Rate"
    const val MetabolicAgeLabel = "Metabolic Age"
    const val BpmUnit = "bpm"
    const val KcalUnit = "kcal"
    const val YearsUnit = "yrs"
    const val LevelUnit = "Lv."
    const val PercentageUnit = "%"
}
