package com.dmdbrands.gurus.weight.features.scaleDetails.strings

import com.dmdbrands.gurus.weight.features.common.helper.ScaleDataHelper

object ScaleDetailsStrings {
  fun deleteConfirmation(sku: String?) = when {
    ScaleDataHelper.isBpmDevice(sku) -> "Are you sure you want to delete this device?"
    else -> "Are you sure you want to delete this scale?"
  }
  const val Delete = "Delete"
  const val Cancel = "Cancel"
  const val DeleteSuccessMessage = "scale deleted successfully"
  const val DeleteErrorMessage = "Error deleting scale"
  const val DeleteLoaderMessage = "Deleting scale..."
  const val Header = "Scale Settings"
  const val Close = "Close"
  const val Mode = "Mode"
  const val AllBodyMetrics = "All Body Metrics"
  const val WeightOnly = "Weight Only"
  const val DisplayMetrics = "Display Metrics"
  const val Users = "Users"
  const val UserNumber = "User Number"
  const val ScaleName = "Scale Name"
  const val Connection = "Connection"
  const val Bluetooth = "Bluetooth"
  const val Connected = "Connected"
  const val WiFi = "Wi-Fi"
  const val WiFiMacAddress = "Wi-Fi MAC Address"
  const val Support = "Support"
  const val ScaleType = "Scale Type"
  const val BluetoothWiFi = "Bluetooth/Wi-Fi"
  const val Sku = "SKU"
  const val DatePaired = "Date Paired"
  const val ProductGuide = "Product Guide"
  const val DeleteScale = "Delete Scale"
  const val SetupIncomplete = "Setup Incomplete"
  const val SetupWifi = "Setup Wi-Fi"

  // Testing Features (similar to Angular implementation)
  const val Others = "Others"
  const val ScaleMac = "Scale MAC"
  const val SoftwareUpdate = "Software Update"
  const val OtherSettings = "Other Settings"
  const val SessionImpedance = "Session Impedance"

  // Firmware Update Strings
  const val Version = "Version"
  const val AlreadyUpToDate = "Your scale is already up to date!"
  const val UpdateMessage = "A new firmware version"
  const val UpdateMessage1 = "is available for your scale."
  const val UpdateMessage2 = "This will update your scale immediately."
  const val UpdateNow = "Now"
  const val UpdateSchedule = "Schedule"
  const val Upgrade = "Upgrade"
  const val Date = "Date"
  const val Save = "Save"

  // Additional Settings Screen Strings
  const val ScaleDetails = "Scale Details"
  const val Manufacturer = "Manufacturer"
  const val DeviceName = "Device Name"
  const val MacAddress = "MAC Address"
  const val BroadcastId = "Broadcast ID"
  const val FirmwareRevision = "Firmware Revision"
  const val BatteryLevel = "Battery Level"
  const val ScaleFeatures = "Scale Features"
  const val EnableStartAnimation = "Enable Start Animation"
  const val EnableEndAnimation = "Enable End Animation"
  const val TimeFormat = "Time Format"
  const val ResetFirmware = "Reset Firmware"
  const val FactoryReset = "Factory Reset"
  const val DownloadLogs = "Download Logs"
  const val ClearScaleData = "Clear Scale Data"
  const val Unknown = "Unknown"
  const val NotSet = "Not Set"
  const val All = "All"
  const val Settings = "Settings"
  const val History = "History"
  const val Account = "Account"

  // ViewModel Toast Messages
  const val SessionImpedanceEnabled = "Session impedance enabled"
  const val SessionImpedanceDisabled = "Session impedance disabled"
  const val ScaleNotConnectedImpedance = "Scale must be connected to change session impedance"
  const val ErrorUpdatingImpedance = "Error updating session impedance"
  const val WifiRequiredForUpdate = "Wi-Fi must be configured to download firmware updates"
  const val UpdatingFirmware = "Updating Firmware..."
  const val FirmwareUpdateStarted = "Firmware update started immediately"
  const val FirmwareUpdateScheduled = "Firmware update scheduled for"
  const val ScaleNotConnectedUpdate = "Scale must be connected to update firmware"
  const val ErrorStartingUpdate = "Error starting firmware update"
  const val DownloadingLogs = "Downloading logs..."
  const val LogsDownloaded = "Logs downloaded successfully"
  const val ScaleNotConnectedLogs = "Scale must be connected to download logs"
  const val ErrorDownloadingLogs = "Error downloading logs"
  const val ClearingData = "Clearing"
  const val DataCleared = "data cleared successfully"
  const val ScaleNotConnectedClear = "Scale must be connected to clear data"
  const val ErrorClearingData = "Error clearing scale data"
  const val UpdatingTimeFormat = "Updating time format..."
  const val TimeFormatUpdated = "Time format updated to"
  const val ScaleNotConnectedTimeFormat = "Scale must be connected to change time format"
  const val ErrorChangingTimeFormat = "Error changing time format"
  const val UpdatingAnimation = "Updating"
  const val AnimationEnabled = "animation enabled"
  const val AnimationDisabled = "animation disabled"
  const val ScaleNotConnectedAnimation = "Scale must be connected to change animation settings"
  const val ErrorUpdatingAnimation = "Error updating animation settings"
  const val ResettingFirmware = "Resetting firmware..."
  const val FirmwareResetSuccess = "Firmware reset successfully"
  const val ScaleNotConnectedReset = "Scale must be connected to reset firmware"
  const val ErrorResettingFirmware = "Error resetting firmware"
  const val RestoringFactory = "Restoring factory settings..."
  const val FactoryRestoreSuccess = "Factory settings restored successfully"
  const val ScaleNotConnectedFactory = "Scale must be connected to restore factory settings"
  const val ErrorRestoringFactory = "Error restoring factory settings"
  const val StartAnimation = "start"
  const val EndAnimation = "end"
  const val TimeFormat12H = "12H"
  const val TimeFormat24H = "24H"
  const val ClearData = "Clear Data"

  // Enable Body Metrics Alert Dialog
  const val EnableBodyMetricsAlertTitle = "Enable Body Metrics"
  const val EnableBodyMetricsAlertMessage = "This will disable Weight Only Mode for one session, and all body metrics will be collected."
  const val EnableBodyMetricsAlertConfirm = "ENABLE"
  const val EnableBodyMetricsAlertCancel = "CANCEL"
  const val EnableBodyMetricsAlertSuccess = "Body metrics enabled successfully"
  const val EnableBodyMetricsAlertError = "Error enabling body metrics"
  const val UpdateMode = "Updating Mode..."
}
