package com.dmdbrands.gurus.weight.features.scaleDetails.strings

object ScaleDetailsStrings {
  const val DeleteScaleConfirmation = "Are you sure you want to delete this scale?"
  const val Delete = "Delete"
  const val Cancel = "Cancel"
  const val DeleteSuccessMessage = "scale deleted successfully"
  const val DeleteErrorMessage = "Error deleting scale"
  const val DeleteLoaderMessage = "Deleting scale..."
  const val Header = "Scale Settings"
  const val Close = "Close"
  const val Settings = "Settings"
  const val Mode = "Mode"
  const val AllBodyMetrics = "All Body Metrics"
  const val WeightOnly = "Weight Only"
  const val DisplayMetrics = "Display Metrics"
  const val Users = "Users"
  const val UserNumber = "User Number"
  const val ScaleName = "Scale Name"
  const val Connection = "Connection"
  const val Bluetooth = "Bluetooth"
  const val Connected = "Connected"
  const val WiFi = "Wi-Fi"
  const val WiFiMacAddress = "Wi-Fi MAC Address"
  const val Support = "Support"
  const val ScaleType = "Scale Type"
  const val BluetoothWiFi = "Bluetooth/Wi-Fi"
  const val Sku = "SKU"
  const val DatePaired = "Date Paired"
  const val ProductGuide = "Product Guide"
  const val DeleteScale = "Delete Scale"
  const val SetupIncomplete = "Setup Incomplete"
  const val SetupWifi = "Setup Wi-Fi"

  // Testing Features (similar to Angular implementation)
  const val Others = "Others"
  const val ScaleMac = "Scale MAC"
  const val SoftwareUpdate = "Software Update"
  const val OtherSettings = "Other Settings"
  const val SessionImpedance = "Session Impedance"

  // Firmware Update Strings
  const val Version = "Version"
  const val AlreadyUpToDate = "Your scale is already up to date!"
  const val UpdateMessage = "A new firmware version"
  const val UpdateMessage1 = "is available for your scale."
  const val UpdateMessage2 = "This will update your scale immediately."
  const val UpdateNow = "Now"
  const val UpdateSchedule = "Schedule"
  const val Upgrade = "Upgrade"
  const val Date = "Date"
  const val Save = "Save"
}
