package com.dmdbrands.gurus.weight.data.storage.db.dao

import androidx.test.ext.junit.runners.AndroidJUnit4
import com.dmdbrands.gurus.weight.data.storage.db.dao.DaoTestFixtures.account
import com.dmdbrands.gurus.weight.data.storage.db.dao.DaoTestFixtures.bodyScaleEntry
import com.dmdbrands.gurus.weight.data.storage.db.dao.DaoTestFixtures.bodyScaleMetric
import com.dmdbrands.gurus.weight.data.storage.db.dao.DaoTestFixtures.bpmEntry
import com.dmdbrands.gurus.weight.data.storage.db.dao.DaoTestFixtures.bpmEntryEntity
import com.dmdbrands.gurus.weight.data.storage.db.dao.DaoTestFixtures.entryEntity
import com.dmdbrands.gurus.weight.data.storage.db.dao.DaoTestFixtures.insertFullAccount
import com.dmdbrands.gurus.weight.data.storage.db.dao.DaoTestFixtures.scaleEntry
import com.google.common.truth.Truth.assertThat
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.Test
import org.junit.runner.RunWith

@OptIn(ExperimentalCoroutinesApi::class)
@RunWith(AndroidJUnit4::class)
class EntryDaoTest : BaseDaoTest() {

    private suspend fun insertParentAccount(accountId: String = "acc-1") {
        accountDao.insertFullAccount(account(id = accountId, email = "$accountId@test.com"))
    }

    /**
     * Insert an entry and soft-delete it. Returns the entry ID.
     */
    private suspend fun insertAndSoftDelete(
        timestamp: String = "2025-06-15T12:00:00.000Z",
        accountId: String = "acc-1",
    ): Long {
        val entry = scaleEntry(accountId = accountId, entryTimestamp = timestamp)
        val entryId = entryDao.insert(entry)
        entryDao.delete(entry.copy(entry = entry.entry.copy(id = entryId)))
        return entryId
    }

    // -------------------------------------------------------------------------
    // insert (Entry) @Transaction — scale
    // -------------------------------------------------------------------------

    @Test
    fun insert_scaleEntry_storesEntryAndSubEntities() = runTest {
        insertParentAccount()
        val entry = scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z")
        val entryId = entryDao.insert(entry)

        assertThat(entryId).isGreaterThan(0L)

        val result = entryDao.getEntryById(entryId)
        assertThat(result).isNotNull()
        assertThat(result?.scaleEntry).isNotNull()
        assertThat(result?.scaleEntry?.weight).isEqualTo(180.0)
        assertThat(result?.scaleEntryMetric).isNotNull()
    }

    @Test
    fun insert_scaleEntry_withoutMetrics() = runTest {
        insertParentAccount()
        val entry = scaleEntry(
            entryTimestamp = "2025-06-15T12:00:00.000Z",
            includeMetrics = false,
        )
        val entryId = entryDao.insert(entry)

        val result = entryDao.getEntryById(entryId)
        assertThat(result?.scaleEntry).isNotNull()
        assertThat(result?.scaleEntryMetric).isNull()
    }

    // -------------------------------------------------------------------------
    // insert (Entry) @Transaction — BPM
    // -------------------------------------------------------------------------

    @Test
    fun insert_bpmEntry_storesEntryAndBpmEntity() = runTest {
        insertParentAccount()
        val entry = bpmEntry(entryTimestamp = "2025-06-15T13:00:00.000Z")
        val entryId = entryDao.insert(entry)

        val result = entryDao.getEntryById(entryId)
        assertThat(result).isNotNull()
        assertThat(result?.bpmEntry).isNotNull()
        assertThat(result?.bpmEntry?.systolic).isEqualTo(120)
    }

    // -------------------------------------------------------------------------
    // insert (List<Entry>)
    // -------------------------------------------------------------------------

    @Test
    fun insert_bulkEntries_storesAll() = runTest {
        insertParentAccount()
        val entries = (1..3).map { i ->
            scaleEntry(
                entryTimestamp = "2025-06-${10 + i}T12:00:00.000Z",
                weight = 180.0 + i,
            )
        }
        entryDao.insert(entries)

        assertThat(entryDao.getEntriesByAccount("acc-1")).hasSize(3)
    }

    @Test
    fun insert_returnsAutoGeneratedId() = runTest {
        insertParentAccount()
        val entryId = entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        assertThat(entryId).isGreaterThan(0L)
    }

    // -------------------------------------------------------------------------
    // update (Entry) @Transaction
    // -------------------------------------------------------------------------

    @Test
    fun update_scaleEntry_modifiesExisting() = runTest {
        insertParentAccount()
        val entry = scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", weight = 180.0)
        val entryId = entryDao.insert(entry)

        val updated = entry.copy(
            entry = entry.entry.copy(id = entryId),
            scale = entry.scale.copy(
                scaleEntry = entry.scale.scaleEntry.copy(id = entryId, weight = 175.0),
                scaleEntryMetric = entry.scale.scaleEntryMetric?.copy(id = entryId),
            ),
        )
        entryDao.update(updated)

        assertThat(entryDao.getEntryById(entryId)?.scaleEntry?.weight).isEqualTo(175.0)
    }

    @Test
    fun update_bpmEntry_modifiesExisting() = runTest {
        insertParentAccount()
        val entry = bpmEntry(entryTimestamp = "2025-06-15T13:00:00.000Z")
        val entryId = entryDao.insert(entry)

        val updated = entry.copy(
            entry = entry.entry.copy(id = entryId),
            bpmEntry = entry.bpmEntry.copy( systolic = 140, diastolic = 90),
        )
        entryDao.update(updated)

        val result = entryDao.getEntryById(entryId)
        assertThat(result?.bpmEntry?.systolic).isEqualTo(140)
        assertThat(result?.bpmEntry?.diastolic).isEqualTo(90)
    }

    /**
     * Regression for the EntryDao.update id-keying bug (MOB-438): child rows were keyed by the
     * @Update row-count (1) instead of the entry id. With two entries, updating the one whose
     * id != 1 must modify the correct row and leave the id-1 row untouched.
     */
    @Test
    fun update_scaleEntry_withIdNotOne_updatesCorrectRow() = runTest {
        insertParentAccount()
        // First entry occupies id 1 so the target's id is not 1.
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T10:00:00.000Z", weight = 100.0))
        val target = scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", weight = 180.0)
        val targetId = entryDao.insert(target)
        assertThat(targetId).isGreaterThan(1L)

        val updated = target.copy(
            entry = target.entry.copy(id = targetId),
            scale = target.scale.copy(
                scaleEntry = target.scale.scaleEntry.copy(id = targetId, weight = 175.0),
                scaleEntryMetric = target.scale.scaleEntryMetric?.copy(id = targetId),
            ),
        )
        entryDao.update(updated)

        assertThat(entryDao.getEntryById(targetId)?.scaleEntry?.weight).isEqualTo(175.0)
        // The id-1 row must be untouched (old bug would have written to it).
        assertThat(entryDao.getEntryById(1L)?.scaleEntry?.weight).isEqualTo(100.0)
    }

    /**
     * `updateScaleNote` sets only the note for the entry's id (id != 1), leaving weight intact (MOB-438).
     */
    @Test
    fun updateScaleNote_setsNoteWithoutTouchingWeight() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T10:00:00.000Z")) // bump id past 1
        val entry = scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", weight = 180.0)
        val id = entryDao.insert(entry)
        assertThat(id).isGreaterThan(1L)

        entryDao.updateScaleNote(id, "doctor visit")

        val result = entryDao.getEntryById(id)
        assertThat(result?.scaleEntry?.note).isEqualTo("doctor visit")
        assertThat(result?.scaleEntry?.weight).isEqualTo(180.0)
    }

    // -------------------------------------------------------------------------
    // Soft delete
    // -------------------------------------------------------------------------

    @Test
    fun delete_setsOperationTypeToDelete() = runTest {
        insertParentAccount()
        val entryId = insertAndSoftDelete()

        // getEntryById filters out deleted entries
        assertThat(entryDao.getEntryById(entryId)).isNull()
        // But the row still exists in the entry table (for sync)
        assertThat(entryDao.getOperationCount("acc-1")).isEqualTo(1)
    }

    @Test
    fun deleteById_hardRemovesEntry() = runTest {
        insertParentAccount()
        val entryId = entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))

        assertThat(entryDao.deleteById(entryId)).isEqualTo(1)
        assertThat(entryDao.getOperationCount("acc-1")).isEqualTo(0)
    }

    @Test
    fun deleteById_returnsZeroForNonexistentId() = runTest {
        assertThat(entryDao.deleteById(999L)).isEqualTo(0)
    }

    @Test
    fun entryView_excludesDeletedEntries() = runTest {
        insertParentAccount()
        insertAndSoftDelete("2025-06-15T12:00:00.000Z")
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-16T12:00:00.000Z"))

        assertThat(entryDao.getEntriesByAccount("acc-1")).hasSize(1)
    }

    // -------------------------------------------------------------------------
    // getLatestEntry (Flow)
    // -------------------------------------------------------------------------

    @Test
    fun getLatestEntry_returnsNewestNonDeleted() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-10T12:00:00.000Z", weight = 180.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", weight = 175.0))

        val result = entryDao.getLatestEntry("acc-1").first()
        assertThat(result).isNotNull()
        assertThat(result?.scaleEntry?.weight).isEqualTo(175.0)
    }

    @Test
    fun getLatestEntry_nullForEmptyAccount() = runTest {
        insertParentAccount()

        assertThat(entryDao.getLatestEntry("acc-1").first()).isNull()
    }

    @Test
    fun getLatestEntry_excludesDeleted() = runTest {
        insertParentAccount()
        insertAndSoftDelete("2025-06-15T12:00:00.000Z")
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-10T12:00:00.000Z", weight = 175.0))

        assertThat(entryDao.getLatestEntry("acc-1").first()?.scaleEntry?.weight).isEqualTo(175.0)
    }

    // -------------------------------------------------------------------------
    // getEntriesByAccount
    // -------------------------------------------------------------------------

    @Test
    fun getEntriesByAccount_returnsAllNonDeleted() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-16T12:00:00.000Z"))

        assertThat(entryDao.getEntriesByAccount("acc-1")).hasSize(2)
    }

    @Test
    fun getEntriesByAccount_isolatesByAccount() = runTest {
        insertParentAccount("acc-1")
        insertParentAccount("acc-2")
        entryDao.insert(scaleEntry(accountId = "acc-1", entryTimestamp = "2025-06-15T12:00:00.000Z"))
        entryDao.insert(scaleEntry(accountId = "acc-2", entryTimestamp = "2025-06-16T12:00:00.000Z"))

        assertThat(entryDao.getEntriesByAccount("acc-1")).hasSize(1)
        assertThat(entryDao.getEntriesByAccount("acc-2")).hasSize(1)
    }

    // -------------------------------------------------------------------------
    // getEntryById
    // -------------------------------------------------------------------------

    @Test
    fun getEntryById_returnsPopulatedEntry() = runTest {
        insertParentAccount()
        val entryId = entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))

        val result = entryDao.getEntryById(entryId)
        assertThat(result).isNotNull()
        assertThat(result?.entry?.accountId).isEqualTo("acc-1")
    }

    @Test
    fun getEntryById_returnsNullForMissing() = runTest {
        assertThat(entryDao.getEntryById(999L)).isNull()
    }

    // -------------------------------------------------------------------------
    // getEntriesByTimeRange
    // -------------------------------------------------------------------------

    @Test
    fun getEntriesByTimeRange_returnsInRange() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-10T12:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-20T12:00:00.000Z"))

        val result = entryDao.getEntriesByTimeRange(
            "acc-1", "2025-06-12T00:00:00.000Z", "2025-06-18T00:00:00.000Z",
        ).first()
        assertThat(result).hasSize(1)
    }

    @Test
    fun getEntriesByTimeRange_dedupsToOnePerDay() = runTest {
        insertParentAccount()
        // Two entries on the same day within the range
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T08:00:00.000Z", weight = 180.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T20:00:00.000Z", weight = 170.0))

        val result = entryDao.getEntriesByTimeRange(
            "acc-1", "2025-06-14T00:00:00.000Z", "2025-06-16T00:00:00.000Z",
        ).first()
        // Query uses MAX(entryTimestamp) GROUP BY day — should return only the latest per day
        assertThat(result).hasSize(1)
        assertThat(result[0].scaleEntry?.weight).isEqualTo(170.0)
    }

    @Test
    fun getEntriesByTimeRange_excludesOutOfRange() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-01-01T12:00:00.000Z"))

        val result = entryDao.getEntriesByTimeRange(
            "acc-1", "2025-06-01T00:00:00.000Z", "2025-06-30T00:00:00.000Z",
        ).first()
        assertThat(result).isEmpty()
    }

    // -------------------------------------------------------------------------
    // getEntriesByDeviceType
    // -------------------------------------------------------------------------

    @Test
    fun getEntriesByDeviceType_filtersCorrectly() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        entryDao.insert(bpmEntry(entryTimestamp = "2025-06-16T12:00:00.000Z"))

        assertThat(entryDao.getEntriesByDeviceType("acc-1", "scale").first()).hasSize(1)
    }

    // -------------------------------------------------------------------------
    // getEntriesByOperationType
    // -------------------------------------------------------------------------

    @Test
    fun getEntriesByOperationType_filtersCorrectly() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", operationType = "create"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-16T12:00:00.000Z", operationType = "update"))

        assertThat(entryDao.getEntriesByOperationType("acc-1", "create").first()).hasSize(1)
    }

    // -------------------------------------------------------------------------
    // Unsynced operations
    // -------------------------------------------------------------------------

    @Test
    fun getUnSynced_returnsUnsyncedEntries() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", isSynced = false))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-16T12:00:00.000Z", isSynced = true))

        assertThat(entryDao.getUnSynced("acc-1")).hasSize(1)
    }

    @Test
    fun incrementAttempts_incrementsCount() = runTest {
        insertParentAccount()
        val entryId = entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))

        entryDao.incrementAttempts(entryId)
        entryDao.incrementAttempts(entryId)

        assertThat(entryDao.getEntryById(entryId)?.entry?.attempts).isEqualTo(2)
    }

    @Test
    fun getFailedOperations_returnsAboveMaxAttempts() = runTest {
        insertParentAccount()
        val entryId = entryDao.insert(
            scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", isSynced = false)
        )
        repeat(3) { entryDao.incrementAttempts(entryId) }

        assertThat(entryDao.getFailedOperations("acc-1", maxAttempts = 3)).hasSize(1)
        assertThat(entryDao.getFailedOperations("acc-1", maxAttempts = 5)).isEmpty()
    }

    @Test
    fun clearUnSynced_removesUnsyncedEntries() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", isSynced = false))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-16T12:00:00.000Z", isSynced = true))

        assertThat(entryDao.clearUnSynced("acc-1")).isEqualTo(1)
        assertThat(entryDao.getOperationCount("acc-1")).isEqualTo(1)
    }

    // -------------------------------------------------------------------------
    // Count queries
    // -------------------------------------------------------------------------

    @Test
    fun getOperationCount_returnsTotal() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-16T12:00:00.000Z"))

        assertThat(entryDao.getOperationCount("acc-1")).isEqualTo(2)
    }

    @Test
    fun getTotalCount_excludesDeleted() = runTest {
        insertParentAccount()
        insertAndSoftDelete("2025-06-15T12:00:00.000Z")
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-16T12:00:00.000Z"))

        assertThat(entryDao.getTotalCount("acc-1")).isEqualTo(1)
    }

    // -------------------------------------------------------------------------
    // Aggregation queries — monthly averages
    // -------------------------------------------------------------------------

    @Test
    fun getMonthlyBodyScaleAveragesWithJoin_computesCorrectAverages() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-10T12:00:00.000Z", weight = 180.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-20T12:00:00.000Z", weight = 170.0))

        val result = entryDao.getMonthlyBodyScaleAveragesWithJoin("acc-1").first()
        assertThat(result).hasSize(1)
        assertThat(result[0].period).isEqualTo("2025-06")
        assertThat(result[0].weight).isWithin(0.1).of(175.0)
    }

    @Test
    fun getMonthlyBodyScaleAveragesWithJoin_groupsAcrossMultipleMonths() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-05-15T12:00:00.000Z", weight = 185.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", weight = 180.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-07-15T12:00:00.000Z", weight = 175.0))

        val result = entryDao.getMonthlyBodyScaleAveragesWithJoin("acc-1").first()
        assertThat(result).hasSize(3)
        // Ordered DESC by period
        assertThat(result[0].period).isEqualTo("2025-07")
        assertThat(result[1].period).isEqualTo("2025-06")
        assertThat(result[2].period).isEqualTo("2025-05")
    }

    // -------------------------------------------------------------------------
    // Aggregation queries — monthly latest
    // -------------------------------------------------------------------------

    @Test
    fun getMonthlyBodyScaleLatestWithJoin_returnsLatestPerMonth() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-10T12:00:00.000Z", weight = 180.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-20T12:00:00.000Z", weight = 170.0))

        val result = entryDao.getMonthlyBodyScaleLatestWithJoin("acc-1").first()
        assertThat(result).hasSize(1)
        assertThat(result[0].weight).isEqualTo(170.0)
    }

    // -------------------------------------------------------------------------
    // Aggregation queries — daily averages
    // -------------------------------------------------------------------------

    @Test
    fun getDaywiseBodyScaleAveragesWithJoin_groupsByDay() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T08:00:00.000Z", weight = 180.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T20:00:00.000Z", weight = 170.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-16T12:00:00.000Z", weight = 175.0))

        assertThat(entryDao.getDaywiseBodyScaleAveragesWithJoin("acc-1").first()).hasSize(2)
    }

    // -------------------------------------------------------------------------
    // Aggregation queries — daily latest
    // -------------------------------------------------------------------------

    @Test
    fun getDaywiseBodyScaleLatestWithJoin_returnsLatestPerDay() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T08:00:00.000Z", weight = 180.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T20:00:00.000Z", weight = 170.0))

        val result = entryDao.getDaywiseBodyScaleLatestWithJoin("acc-1").first()
        assertThat(result).hasSize(1)
        assertThat(result[0].weight).isEqualTo(170.0)
    }

    // -------------------------------------------------------------------------
    // getMonthDetail
    // -------------------------------------------------------------------------

    @Test
    fun getMonthDetail_returnsEntriesForMonth() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-07-15T12:00:00.000Z"))

        assertThat(entryDao.getMonthDetail("acc-1", "2025-06").first()).hasSize(1)
    }

    // -------------------------------------------------------------------------
    // History queries
    // -------------------------------------------------------------------------

    @Test
    fun getMonthlyHistory_returnsMonthNamesAndWeightChange() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-01T12:00:00.000Z", weight = 180.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-30T12:00:00.000Z", weight = 175.0))

        val result = entryDao.getMonthlyHistory("acc-1").first()
        assertThat(result).isNotEmpty()
        val june = result[0]
        assertThat(june.entryTimestamp).contains("Jun")
        assertThat(june.change).isWithin(0.1).of(-5.0)
        assertThat(june.entryCount).isEqualTo(2)
    }

    @Test
    fun getMonthlyHistoryLastYear_filtersToLast365Days() = runTest {
        insertParentAccount()
        // Entry within last year (use a recent date)
        entryDao.insert(scaleEntry(entryTimestamp = "2026-03-01T12:00:00.000Z", weight = 175.0))
        // Entry older than 365 days
        entryDao.insert(scaleEntry(entryTimestamp = "2024-01-01T12:00:00.000Z", weight = 200.0))

        val result = entryDao.getMonthlyHistoryLastYear("acc-1").first()
        // Recent entry must appear, old entry must be excluded
        assertThat(result).hasSize(1)
        assertThat(result[0].entryTimestamp).contains("Mar")
    }

    // -------------------------------------------------------------------------
    // Streak queries
    // -------------------------------------------------------------------------

    @Test
    fun getStreakData_returnsOneDatePerDay() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T08:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T20:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-16T12:00:00.000Z"))

        assertThat(entryDao.getStreakData("acc-1")).hasSize(2)
    }

    @Test
    fun getLongestStreakCount_countsConsecutiveDays() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-16T12:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-17T12:00:00.000Z"))
        // Gap
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-20T12:00:00.000Z"))

        assertThat(entryDao.getLongestStreakCount("acc-1")).isEqualTo(3)
    }

    @Test
    fun getLongestStreakCount_returnsZeroForEmptyAccount() = runTest {
        insertParentAccount()
        assertThat(entryDao.getLongestStreakCount("acc-1")).isEqualTo(0)
    }

    // -------------------------------------------------------------------------
    // Metrics
    // -------------------------------------------------------------------------

    @Test
    fun getMetricsByEntryId_returnsMetrics() = runTest {
        insertParentAccount()
        val entryId = entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))

        val result = entryDao.getMetricsByEntryId(entryId).first()
        assertThat(result.bmr).isEqualTo(1800.0)
        assertThat(result.pulse).isEqualTo(72)
    }

    @Test
    fun getScaleEntryById_returnsScaleEntry() = runTest {
        insertParentAccount()
        val entryId = entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", weight = 180.0))

        val result = entryDao.getScaleEntryById(entryId)
        assertThat(result).isNotNull()
        assertThat(result?.weight).isEqualTo(180.0)
    }

    // -------------------------------------------------------------------------
    // Bulk insert (raw entities)
    // -------------------------------------------------------------------------

    @Test
    fun insertEntries_bulkInsertRawEntities() = runTest {
        insertParentAccount()
        val entities = (1..3).map { i ->
            entryEntity(entryTimestamp = "2025-06-${10 + i}T12:00:00.000Z")
        }
        val ids = entryDao.insertEntries(entities)
        assertThat(ids).hasSize(3)
        assertThat(ids.all { it > 0 }).isTrue()
    }

    @Test
    fun insertBpmList_bulkInsert() = runTest {
        insertParentAccount()
        val id1 = entryDao.insertEntryEntity(entryEntity(entryTimestamp = "2025-06-15T12:00:00.000Z", deviceType = "bpm"))
        val id2 = entryDao.insertEntryEntity(entryEntity(entryTimestamp = "2025-06-16T12:00:00.000Z", deviceType = "bpm"))

        entryDao.insertBpmList(listOf(bpmEntryEntity(id = id1), bpmEntryEntity(id = id2)))

        assertThat(entryDao.getEntryById(id1)?.bpmEntry).isNotNull()
    }

    @Test
    fun insertBodyScales_bulkInsert() = runTest {
        insertParentAccount()
        val id1 = entryDao.insertEntryEntity(entryEntity(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        val id2 = entryDao.insertEntryEntity(entryEntity(entryTimestamp = "2025-06-16T12:00:00.000Z"))

        entryDao.insertBodyScales(listOf(bodyScaleEntry(id = id1), bodyScaleEntry(id = id2)))

        assertThat(entryDao.getScaleEntryById(id1)).isNotNull()
        assertThat(entryDao.getScaleEntryById(id2)).isNotNull()
    }

    @Test
    fun insertScaleEntries_bulkInsert() = runTest {
        insertParentAccount()
        val id1 = entryDao.insertEntryEntity(entryEntity(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        val id2 = entryDao.insertEntryEntity(entryEntity(entryTimestamp = "2025-06-16T12:00:00.000Z"))

        entryDao.insertScaleEntries(listOf(bodyScaleEntry(id = id1), bodyScaleEntry(id = id2)))

        assertThat(entryDao.getScaleEntryById(id1)).isNotNull()
        assertThat(entryDao.getScaleEntryById(id2)).isNotNull()
    }

    @Test
    fun insertBodyScaleMetrics_bulkInsert() = runTest {
        insertParentAccount()
        val id1 = entryDao.insertEntryEntity(entryEntity(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        val id2 = entryDao.insertEntryEntity(entryEntity(entryTimestamp = "2025-06-16T12:00:00.000Z"))
        entryDao.insertBodyScale(bodyScaleEntry(id = id1))
        entryDao.insertBodyScale(bodyScaleEntry(id = id2))

        entryDao.insertBodyScaleMetrics(listOf(bodyScaleMetric(id = id1), bodyScaleMetric(id = id2)))

        assertThat(entryDao.getMetricsByEntryId(id1).first()).isNotNull()
        assertThat(entryDao.getMetricsByEntryId(id2).first()).isNotNull()
    }

    // -------------------------------------------------------------------------
    // updateBodyScaleMetric
    // -------------------------------------------------------------------------

    @Test
    fun updateBodyScaleMetric_modifiesExisting() = runTest {
        insertParentAccount()
        val entryId = entryDao.insertEntryEntity(entryEntity(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        entryDao.insertBodyScale(bodyScaleEntry(id = entryId))
        entryDao.insertBodyScaleMetric(bodyScaleMetric(id = entryId, bmr = 1800.0, pulse = 72))

        entryDao.updateBodyScaleMetric(bodyScaleMetric(id = entryId, bmr = 2000.0, pulse = 80))

        val result = entryDao.getMetricsByEntryId(entryId).first()
        assertThat(result.bmr).isEqualTo(2000.0)
        assertThat(result.pulse).isEqualTo(80)
    }

    // -------------------------------------------------------------------------
    // CASCADE from account delete
    // -------------------------------------------------------------------------

    @Test
    fun deleteAccount_cascadesToEntries() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))

        accountDao.deleteAccountById("acc-1")
        assertThat(entryDao.getOperationCount("acc-1")).isEqualTo(0)
    }

    @Test
    fun deleteAccount_cascadesToSubEntities() = runTest {
        insertParentAccount()
        val entryId = entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))

        accountDao.deleteAccountById("acc-1")
        assertThat(entryDao.getScaleEntryById(entryId)).isNull()
    }

    // -------------------------------------------------------------------------
    // deleteAllEntriesForAccount
    // -------------------------------------------------------------------------

    @Test
    fun deleteAllEntriesForAccount_removesAllEntries() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-16T12:00:00.000Z"))

        assertThat(entryDao.deleteAllEntriesForAccount("acc-1")).isEqualTo(2)
        assertThat(entryDao.getOperationCount("acc-1")).isEqualTo(0)
    }

    // -------------------------------------------------------------------------
    // getEntriesInRange
    // -------------------------------------------------------------------------

    @Test
    fun getEntriesInRange_returnsInRange() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-10T12:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-20T12:00:00.000Z"))

        val result = entryDao.getEntriesInRange(
            "acc-1", "2025-06-12T00:00:00.000Z", "2025-06-18T00:00:00.000Z",
        ).first()
        assertThat(result).hasSize(1)
    }

    // -------------------------------------------------------------------------
    // getEntriesSince
    // -------------------------------------------------------------------------

    @Test
    fun getEntriesSince_returnsEntriesAfterDate() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-10T12:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-20T12:00:00.000Z"))

        assertThat(entryDao.getEntriesSince("acc-1", "2025-06-14T00:00:00.000Z").first()).hasSize(2)
    }

    // -------------------------------------------------------------------------
    // getOldestEntry
    // -------------------------------------------------------------------------

    @Test
    fun getOldestEntry_returnsOldest() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", weight = 180.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-10T12:00:00.000Z", weight = 185.0))

        val result = entryDao.getOldestEntry("acc-1")
        assertThat(result).isNotNull()
        assertThat(result?.scaleEntry?.weight).isEqualTo(185.0)
    }

    @Test
    fun getOldestEntry_returnsNullForEmptyAccount() = runTest {
        insertParentAccount()

        assertThat(entryDao.getOldestEntry("acc-1")).isNull()
    }

    @Test
    fun getOldestEntry_excludesDeleted() = runTest {
        insertParentAccount()
        insertAndSoftDelete("2025-06-10T12:00:00.000Z")
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", weight = 180.0))

        val result = entryDao.getOldestEntry("acc-1")
        assertThat(result?.scaleEntry?.weight).isEqualTo(180.0)
    }

    // -------------------------------------------------------------------------
    // Flow reactivity (verify emissions after mutations)
    // -------------------------------------------------------------------------

    @Test
    fun getLatestEntry_emitsUpdatedValueAfterNewInsert() = runTest {
        insertParentAccount()

        assertThat(entryDao.getLatestEntry("acc-1").first()).isNull()

        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", weight = 180.0))

        assertThat(entryDao.getLatestEntry("acc-1").first()?.scaleEntry?.weight).isEqualTo(180.0)
    }

    @Test
    fun getEntriesByDeviceType_reactsToNewEntries() = runTest {
        insertParentAccount()

        assertThat(entryDao.getEntriesByDeviceType("acc-1", "scale").first()).isEmpty()

        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))

        assertThat(entryDao.getEntriesByDeviceType("acc-1", "scale").first()).hasSize(1)
    }

    @Test
    fun getMonthDetail_reactsToNewEntries() = runTest {
        insertParentAccount()

        assertThat(entryDao.getMonthDetail("acc-1", "2025-06").first()).isEmpty()

        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z"))

        assertThat(entryDao.getMonthDetail("acc-1", "2025-06").first()).hasSize(1)
    }

    // -------------------------------------------------------------------------
    // Cross-account isolation
    // -------------------------------------------------------------------------

    @Test
    fun getLatestEntry_isolatesByAccount() = runTest {
        insertParentAccount("acc-1")
        insertParentAccount("acc-2")
        entryDao.insert(scaleEntry(accountId = "acc-1", entryTimestamp = "2025-06-15T12:00:00.000Z", weight = 180.0))
        entryDao.insert(scaleEntry(accountId = "acc-2", entryTimestamp = "2025-06-16T12:00:00.000Z", weight = 170.0))

        assertThat(entryDao.getLatestEntry("acc-1").first()?.scaleEntry?.weight).isEqualTo(180.0)
        assertThat(entryDao.getLatestEntry("acc-2").first()?.scaleEntry?.weight).isEqualTo(170.0)
    }

    @Test
    fun getUnSynced_isolatesByAccount() = runTest {
        insertParentAccount("acc-1")
        insertParentAccount("acc-2")
        entryDao.insert(scaleEntry(accountId = "acc-1", entryTimestamp = "2025-06-15T12:00:00.000Z", isSynced = false))
        entryDao.insert(scaleEntry(accountId = "acc-2", entryTimestamp = "2025-06-16T12:00:00.000Z", isSynced = false))

        assertThat(entryDao.getUnSynced("acc-1")).hasSize(1)
        assertThat(entryDao.getUnSynced("acc-2")).hasSize(1)
    }

    @Test
    fun deleteAllEntriesForAccount_isolatesByAccount() = runTest {
        insertParentAccount("acc-1")
        insertParentAccount("acc-2")
        entryDao.insert(scaleEntry(accountId = "acc-1", entryTimestamp = "2025-06-15T12:00:00.000Z"))
        entryDao.insert(scaleEntry(accountId = "acc-2", entryTimestamp = "2025-06-16T12:00:00.000Z"))

        entryDao.deleteAllEntriesForAccount("acc-1")

        assertThat(entryDao.getOperationCount("acc-1")).isEqualTo(0)
        assertThat(entryDao.getOperationCount("acc-2")).isEqualTo(1)
    }

    // -------------------------------------------------------------------------
    // Edge cases
    // -------------------------------------------------------------------------

    @Test
    fun getOperationCount_returnsZeroForEmptyAccount() = runTest {
        insertParentAccount()
        assertThat(entryDao.getOperationCount("acc-1")).isEqualTo(0)
    }

    @Test
    fun getTotalCount_returnsZeroForEmptyAccount() = runTest {
        insertParentAccount()
        assertThat(entryDao.getTotalCount("acc-1")).isEqualTo(0)
    }

    @Test
    fun deleteAllEntriesForAccount_returnsZeroForEmptyAccount() = runTest {
        insertParentAccount()
        assertThat(entryDao.deleteAllEntriesForAccount("acc-1")).isEqualTo(0)
    }

    @Test
    fun clearUnSynced_returnsZeroWhenNoneUnsynced() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", isSynced = true))

        assertThat(entryDao.clearUnSynced("acc-1")).isEqualTo(0)
    }

    @Test
    fun getUnSynced_returnsEmptyWhenAllSynced() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", isSynced = true))

        assertThat(entryDao.getUnSynced("acc-1")).isEmpty()
    }

    @Test
    fun getFailedOperations_returnsEmptyWhenNoEntries() = runTest {
        insertParentAccount()
        assertThat(entryDao.getFailedOperations("acc-1", maxAttempts = 3)).isEmpty()
    }

    @Test
    fun incrementAttempts_returnsZeroForNonexistentId() = runTest {
        assertThat(entryDao.incrementAttempts(999L)).isEqualTo(0)
    }

    @Test
    fun insert_emptyList_noOp() = runTest {
        insertParentAccount()
        entryDao.insert(emptyList())
        assertThat(entryDao.getOperationCount("acc-1")).isEqualTo(0)
    }

    @Test
    fun getEntriesByOperationType_includesDeletedEntries() = runTest {
        insertParentAccount()
        insertAndSoftDelete("2025-06-15T12:00:00.000Z")

        // getEntriesByOperationType queries entry table (not entry_view), so it includes deleted
        val result = entryDao.getEntriesByOperationType("acc-1", "delete").first()
        assertThat(result).hasSize(1)
    }

    // -------------------------------------------------------------------------
    // Conflict strategy
    // -------------------------------------------------------------------------

    @Test
    fun insertEntryEntity_replacesOnDuplicateUniqueIndex() = runTest {
        insertParentAccount()
        // EntryEntity has unique index on (accountId, entryTimestamp)
        val id1 = entryDao.insertEntryEntity(
            entryEntity(entryTimestamp = "2025-06-15T12:00:00.000Z", operationType = "create")
        )
        val id2 = entryDao.insertEntryEntity(
            entryEntity(entryTimestamp = "2025-06-15T12:00:00.000Z", operationType = "update")
        )

        // REPLACE removes old row, inserts new — new ID assigned
        assertThat(id2).isNotEqualTo(id1)
        assertThat(entryDao.getOperationCount("acc-1")).isEqualTo(1)
    }

    // -------------------------------------------------------------------------
    // Daily average value verification
    // -------------------------------------------------------------------------

    @Test
    fun getDaywiseBodyScaleAveragesWithJoin_computesCorrectAverage() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T08:00:00.000Z", weight = 180.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T20:00:00.000Z", weight = 170.0))

        val result = entryDao.getDaywiseBodyScaleAveragesWithJoin("acc-1").first()
        assertThat(result).hasSize(1)
        assertThat(result[0].weight).isWithin(0.1).of(175.0)
    }

    // -------------------------------------------------------------------------
    // Monthly history across multiple months
    // -------------------------------------------------------------------------

    @Test
    fun getMonthlyHistory_groupsAcrossMultipleMonths() = runTest {
        insertParentAccount()
        entryDao.insert(scaleEntry(entryTimestamp = "2025-05-15T12:00:00.000Z", weight = 185.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-06-15T12:00:00.000Z", weight = 180.0))
        entryDao.insert(scaleEntry(entryTimestamp = "2025-07-15T12:00:00.000Z", weight = 175.0))

        val result = entryDao.getMonthlyHistory("acc-1").first()
        assertThat(result).hasSize(3)
        // Ordered DESC by period
        assertThat(result[0].entryTimestamp).contains("Jul")
        assertThat(result[1].entryTimestamp).contains("Jun")
        assertThat(result[2].entryTimestamp).contains("May")
    }
}
