package com.greatergoods.meapp.features.ScaleSetup.enums

enum class ScaleConnectionStatusType {
  WAKEUP_R4,
  WAKEUP_A6,
  WAKEUP_A3,
  CONNECTING,
  ERROR,
  UPDATE_SETTINGS,
  BLUETOOTH_CONNECTING,
  BLUETOOTH_ERROR,
  GATHERING_NETWORK,
  NO_NETWORK_ERROR,
  WIFI_LIST,
  WIFI_CONNECTING,
  WIFI_ERROR,
  TAKING_MEASUREMENT,
  UPDATE_SETTINGS_ERROR,
  COLLECTING_MEASUREMENT_ERROR,
}

enum class ScaleDetailLoader {
  NONE,
  LOAD_WIFI_MAC_ADDRESS,
  LOAD_SCALE_USERS,
  LOAD_CONNECTED_WIFI_SSID,
}

enum class ScaleSetupError {
  NONE,
  BLUETOOTH_CONNECTION_FAILED,
  DUPLICATES_FOUND,
  MAX_USER_REACHED,
  NO_NETWORK_FOUND,
  WIFI_CONNECTION_FAILED,
  UPDATE_SETTINGS_FAILED,
  COLLECT_MEASUREMENT_FAILED,
}
