package com.greatergoods.meapp.features.ScaleSetup.enums

enum class BtWifiSetupStep {
  SCALE_INFO,
  PERMISSIONS,
  WAKEUP,
  CONNECTING_BLUETOOTH,
  GATHERING_NETWORK,
  DUPLICATES_FOUND,
  AVAILABLE_WIFI_LIST,
  WIFI_PASSWORD,
  CONNECTING_WIFI,
  CUSTOMIZE_SETTINGS,
  UPDATE_SETTINGS,
  STEP_ON,
  MEASUREMENT,
  SCALE_CONNECTED,
}

enum class WifiScaleSetupStep {
  SCALE_INFO,
  PERMISSIONS,
  WIFI_PASSWORD,
  SELECT_USER,
  ACTIVATE_SCALE,
  CONNECTING_SCALE,
  ERROR_GUIDE,
  TROUBLE_SHOOTING,
  SWITCH_WIFI,
  SCALE_COUNTS,
  STEP_ON,
  SCALE_CONNECTED,
}

enum class BtScaleSetupStep {
  SCALE_INFO,
  PERMISSIONS,
  SELECT_USER,
  CONNECTING_BLUETOOTH,
  FIND_USER,
  STEP_ON,
  SETUP_FINISHED,
}

enum class LcbtScaleSetupStep {
  SCALE_INFO,
  PERMISSIONS,
  STEP_ON,
  CONNECTING_BLUETOOTH,
  SETUP_FINISHED,
}

enum class AppsyncScaleSetupStep {
  SCALE_INFO,
  PERMISSIONS,
  ACTIVATE_SCALE,
  ADD_INFO,
  STEP_ON,
  OPEN_CAMERA,
  SETUP_FINISHED,
}

enum class CustomizeSettings(
  val value: Int,
) {
  NONE(-1),
  DASHBOARD_METRICS(0),
  SCALE_METRICS(1),
  SCALE_MODE(2),
  SCALE_USERNAME(3),
}
