name: CI / unit-tests

on:
  pull_request:
    branches: ['**']
  push:
    branches: [dev, main]

jobs:
  unit-tests:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Resolve Swift Package Dependencies
        working-directory: iOS
        run: |
          xcodebuild -resolvePackageDependencies \
            -project meApp.xcodeproj

      - name: Boot Simulator
        run: |
          xcrun simctl boot "iPhone 16" || true

      # - name: Run Unit Tests
      #   working-directory: iOS
      #   run: |
      #     xcodebuild test \
      #       -project meApp.xcodeproj \
      #       -scheme meApp \
      #       -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
      #       -only-testing:meAppTests \
      #       CODE_SIGN_IDENTITY="" \
      #       CODE_SIGNING_REQUIRED=NO \
      #       CODE_SIGNING_ALLOWED=NO \
      #       ENABLE_USER_SCRIPT_SANDBOXING=NO
