import Foundation
import HealthKit
import ggHealthKitPackage
import SwiftData

@MainActor
public final class HealthKitService: HealthKitServiceProtocol {
    static let shared = HealthKitService()
    @Injector private var integrationService: IntegrationsService
    @Injector private var logger: LoggerService
    private let hkPackage = ggHealthKitPackage.AppleHealthHandler.shared
    private let tag = "HealthKitService"
    private let context: ModelContext
    
    // MARK: - Initialization
    
    init() {
        hkPackage.setAppType(appType: .WEIGHT_GURUS)
        self.context = PersistenceController.shared.context
    }
    
    // MARK: - HealthKitServiceProtocol
    
    /// Integrates or de-integrates Apple Health based on `turnOn`. Returns `true` when integration remains enabled after the call.
    public func integrate(turnOn: Bool) async throws -> Bool {
        if turnOn {
            do {
                let isAlreadyIntegrated = try await integrationService.isIntegrationAlreadyUsed(type: .healthKit)
                if isAlreadyIntegrated {
                    throw IntegrationError.userConflict
                }
            } catch {
                throw IntegrationError.userConflict
            }
        }
        
        if turnOn {
            let isAvailable = hkPackage.available();
            if !isAvailable {
                // TODO: Handle case where HealthKit is not available
                return false
            }
            let _ = await hkPackage.requestAuthorization()
            let permissions = getApprovedPermissionList()
            if permissions.isEmpty {
                return false
            }
            let integrationInfo = IntegrationInfo(
                type: .healthKit,
                isIntegrated: true
            )
            do {
                try await self.integrationService.setStoredIntegrationData(integrationInfo)
                return true
            } catch {
                return false
            }
        } else {
            try await clearHealthKit()
            return false
        }
    }
    
    /// Pushes the entire local entry history into Apple Health.
    public func syncAllData() async throws {
        let entries = try await fetchAllEntries()
        let healthKitData = buildHealthKitData(from: entries)
        try await hkPackage.saveData(healthKitData)
    }
    
    /// Opens the Apple Health app so the user can review permissions.
    public func openAppleHealth() {
        Task {
            await hkPackage.openAppleHealth()
        }
    }
    
    /// Writes a single `Entry` into Apple Health.
    func syncNewData(entry: Entry) async throws {
        let healthKitData = buildHealthKitData(from: [entry])
        try await hkPackage.saveData(healthKitData)
    }
    
    /// Deletes a single `Entry` previously written to Apple Health.
    func deleteEntry(entry: Entry) async throws -> Bool {
        let healthKitData = buildHealthKitData(from: [entry])
        try await hkPackage.deleteEntry(healthKitData)
        return true
    }
    
    /// Removes all Apple Health records previously generated by the app.
    public func clearHealthKit() async throws {
        let integrationInfo = IntegrationInfo(
            type: .healthKit,
            isIntegrated: false
        )
        do {
            try await self.integrationService.setStoredIntegrationData(integrationInfo)
        } catch {
        }
        try await hkPackage.deleteAllData()
    }
    
    /// Returns `true` if at least one HealthKit permission is granted.
    func checkAuthorizationStatus() -> Bool {
        let approvedPermissionList = self.getApprovedPermissionList();
        return approvedPermissionList.count > 0
    }
    
    /// Lists the granted HealthKit permission identifiers.
    func getApprovedPermissionList() -> [String] {
        hkPackage.getApprovedPermissionList()
    }
    
    // MARK: - Private Helpers ------------------------------------------------
    
    /// Fetches all entries from the local database ordered chronologically.
    private func fetchAllEntries() async throws -> [Entry] {
        let descriptor = FetchDescriptor<Entry>(
            sortBy: [SortDescriptor(\.entryTimestamp, order: .forward)]
        )
        return try context.fetch(descriptor)
    }
    
    /// Converts entries into `HealthKitData` payloads ready for saving.
    private func buildHealthKitData(from entries: [Entry]) -> [HealthKitData] {
        var healthKitData: [HealthKitData] = []
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        for entry in entries {
            guard let scaleEntry = entry.scaleEntry,
                  let timestamp = formatter.date(from: entry.entryTimestamp) else {
                continue
            }
            
            if let weight = scaleEntry.weight {
                healthKitData.append(HealthKitData(
                    type: .weight,
                    value: ConversionTools.convertStoredToLbs(weight),
                    timestamp: timestamp
                ))
            }
            
            if let bodyFat = scaleEntry.bodyFat {
                healthKitData.append(HealthKitData(
                    type: .bodyFat,
                    value: ConversionTools.convertStoredToLbs(bodyFat),
                    timestamp: timestamp
                ))
            }
            
            if let muscleMass = scaleEntry.muscleMass {
                healthKitData.append(HealthKitData(
                    type: .leanBodyMass,
                    value: ConversionTools.convertStoredToLbs(muscleMass),
                    timestamp: timestamp
                ))
            }
            
            if let weight = scaleEntry.weight, let bodyFat = scaleEntry.bodyFat {
                let convertedWeight = ConversionTools.convertStoredToLbs(weight)
                let convertedBodyFat = ConversionTools.convertStoredToLbs(bodyFat)
                let leanBodyMass = convertedWeight - (convertedWeight * (convertedBodyFat / 100))
                healthKitData.append(HealthKitData(
                    type: .leanBodyMass,
                    value: leanBodyMass,
                    timestamp: timestamp
                ))
            }
            
            if let bmi = scaleEntry.bmi {
                healthKitData.append(HealthKitData(
                    type: .bmi,
                    value: ConversionTools.convertStoredToLbs(bmi),
                    timestamp: timestamp
                ))
            }
        }
        
        return healthKitData
    }
    
    /// Writes the provided dataset to Apple Health and logs the outcome.
    private func saveHealthKitData(finalData: [HealthKitData]) async throws {
        do {
            if finalData.count > 0 {
                try await hkPackage.saveData(finalData)
            } else {
                logger.log(level: .info, tag: tag, message: "HealthKit: No data to save")
            }
        } catch {
            logger.log(level: .error, tag: tag, message: "HealthKit: saveHealthKitData error", data: error)
            throw error
        }
    }
}

